### PR TITLE
new chainspec for testnet

### PR DESCRIPTION
**Pull request by lovelaced**
raw json

### CODE REVIEW

**Comment by ascjones** [comment]
The stash balance is only 1.142 units:

Screenshot from 2020-10-14 22-44-14

But the total issuance is quite a bit higher:

image

I believe it should be a lot more

**Comment by lovelaced** [comment]
Half of it is in the faucet account.

**Comment by ascjones** [comment]
> Half of it is in the faucet account.

I thought an MUnit was 1,000,000 units not 1,000? 

By the way my local chain is syncing now :rocket: 

Screenshot from 2020-10-14 23-06-36

**Comment by ascjones** [comment]
@lovelaced could we get the non raw chainspec here so we can read the settings?

**Review by ascjones — APPROVED** [review]

**Review by Robbepop — APPROVED** [review]

**Pull request merged**
