### PR TITLE
Parachain integration

### LINKED ISSUE #30: Parachain
Currently `canvas` runs as a solo chain, but ultimately it should be a parachain. This will involve migrating to use `cumulus`, and if possible still allow it to run as a solochain for the testnet,  [Moonbeam](https://github.com/PureStake/moonbeam) appear to have achieved something along those lines.

According to @athei, there are still some outstanding issues which need to be resolved before the `contracts` pallet will work on a parachain:

- [ ] Storage transactions
- [ ] Child tries

### PR DESCRIPTION
**Pull request by ascjones**
Closes #30

Converts the node from a solo chain to run as a parachain.

Initially we considered continuing to support running the node as a solo chain for local development and for the existing canvas testnet. However after some experimentation we concluded that the cost of introducing the extra code paths would increase the long term maintenance burden of the codebase. 

So to keep things simple, running this node requires (for now) a running relay chain environment. The upside is that we are running it as a parachain all the way through the development and testing environments so we can test any parachain specific features e.g. cross-chain contract calls. The downside is that it increases the complexity of the local development setup. This should be made easier by using `polkadot-launch`, for which I have provided a configuration as part of this PR. We could also further make this easier by providing a docker container with prebuilt polkadot binaries for the relay chain.

# todo

- [ ] document in README for local development testnet
- [ ] generate canvas testnet chainspecs

### CODE REVIEW

**Comment by riusricardo** [comment]
I liked the idea of having a solo-chain and a parachain. I agree that it adds a little bit of maintenance burden but not so much in my opinion. I have done it and could take a peak on this after merging this PR.
An alternative would be to ask users to run this configuration and in case that they don't have enough power on their machines to handle several nodes, then we can point them to the add contracts pallet tutorial to create a standalone chain.

My main concern is people that is ramping up.  What are the short and long term plans for this parachain? Rococo gets a reset quite often and it is WIP. Are we gonna add this friction to the users instead of a standalone testent?

**Comment by Robbepop** [comment]
The plan is to have our own test net with a single relay chain and a single Canvas parachain. In the future we want to extend this to two Canvas parachains so that we can research with contract calling other contracts on other parachains etc.

**Comment by riusricardo** [comment]
Thanks for the explanation @Robbepop. Sounds as a good plan. Looking forward to see the next contracts development :)

**Comment by ascjones** [comment]
> I liked the idea of having a solo-chain and a parachain. I agree that it adds a little bit of maintenance burden but not so much in my opinion

Happy to add the solo chain mode back as a future PR if there's a need for it and we can make it nice and simple.

>  I have done it and could take a peak

Please do. Out of interest where have you done this already. I was looking at the moonbeam as an example, but theirs only allows a single node parachain locally (which might be enough even).

**Comment by riusricardo** [comment]
>Please do. Out of interest where have you done this already. I was looking at the moonbeam as an example, but theirs only allows a single node parachain locally (which might be enough even).

I did a template that was using features to hide the different dependencies. An interesting example to learn from is PolkaBTC https://github.com/interlay/btc-parachain they also used features and their code worked in the Rococo network.

**Review by riusricardo — APPROVED** [review]
Works pretty well. 
Tested on Polkadot/Rococo commit `575a89e`

**Comment by ascjones** [comment]
> > Please do. Out of interest where have you done this already. I was looking at the moonbeam as an example, but theirs only allows a single node parachain locally (which might be enough even).
> 
> I did a template that was using features to hide the different dependencies. An interesting example to learn from is PolkaBTC https://github.com/interlay/btc-parachain they also used features and their code worked in the Rococo network.

I wish I had looked at this originally, I did try briefly something similar but it was taking too much effort. Even then it has lots of feature blocked code which does slightly increase complexity/maintainability. So decided to keep this as simple as possible for now to get parachains working.

**Comment by ascjones** [comment]
Parachain work will continue on the `rococo-v1` branch, following the convention from `cumulus`/`polakdot`/`substrate`. This means that `master` will remain a solo chain (for now) for local dev chains and the existing testnet.

**Pull request merged**
